export const LOAD_SERVICE="LOAD_SERVICE";
export const LOAD_SERVICE_SUCCESS="LOAD_SERVICE_SUCCESS";
export const LOAD_SERVICE_FAILURE="LOAD_SERVICE_FAILURE";

export const LOAD_PAYMENT="LOAD_PAYMENT";
export const LOAD_PAYMENT_SUCCESS="LOAD_PAYMENT_SUCCESS";
export const LOAD_PAYMENT_FAILURE="LOAD_PAYMENT_FAILURE";